# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

spring:
  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      javax.persistence.sql-load-script-source: data.sql
  datasource:
    url: jdbc:h2:mem:jjpahib;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
